let Env = {
  REACT_APP_GRAPHQL_SERVER: undefined,
  REACT_APP_FIREBASE_API_KEY: undefined,
  REACT_APP_FIREBASE_AUTH_DOMAIN: undefined,
  REACT_APP_FIREBASE_PROJECT_ID: undefined,
  REACT_APP_FIREBASE_STORAGE_BUCKET: undefined,
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: undefined,
  REACT_APP_FIREBASE_APP_ID: undefined,
  REACT_APP_FIREBASE_MEASURENT_ID: undefined,
  REACT_APP_GRAPHQL_SUBSCRIPTION_ENDPOINT: undefined,
}

Env = window.env || process.env;

export default Env;